### ISSUE TITLE
Memory leak at the beginning of pretraining

### ISSUE THREAD

**Issue by chanyn** [facebookresearch/DepthContrast#22]
Hi, I always meet memory explosion and the pretraining is interrupted:

The interrupt happened at the different iteration, maybe epoch 1 or 5 or ....

Traceback (most recent call last):
  File "main.py", line 197, in <module>
    main()
  File "main.py", line 74, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args, cfg))
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/xuhang/anaconda3/envs/depthcontrast/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 108, in join
    (error_index, name)
Exception: process 0 terminated with signal SIGFPE

**Comment by chanyn** [comment]
And the other question, is there a resume mechanism?

If I re-run the process in the same folder, the training always starts from epoch 0.

**Comment by zaiweizhang** [comment]
Hi, would you mind providing some context? Which models are you trying to train (pointnet or voxel based networks)?
