### ISSUE TITLE
Running VoteNet on Matterport3D

### ISSUE THREAD

**Issue by memoiry** [facebookresearch/DepthContrast#3]
Hi,

Thanks for your great work.

I'm currently working on reproducing results on Matterport3D, and I just follow README in this fork of votenet https://github.com/zaiweizhang/votenet/tree/master/mp3d. But when I try to download mp3d dataset and process it for the experiments, I found that mp3d dataset is quite different from scannet, which means I can not find `*_vh_clean_2.ply`, `*aggregation.json`, `*_vh_clean_2.0.010000.segs.json` and metadata for mp3d dataset used in batch_load_scannet_data.py. 

So could you please make it more clear about how to prepare mp3d dataset for the votenet experiments?

Thanks!

**Comment by imisra** [comment]
Thanks for your interest! @zaiweizhang should know more about this.

**Comment by zaiweizhang** [comment]
Thanks for the note! I have updated the folked votenet repo. There is a script to process the matterport data now.

**Comment by memoiry** [comment]
Hi, @zaiweizhang @imisra 

Thanks for your quick reply.

I just downloaded `region segmentation` files and category mapping from here https://github.com/matterport/3d-dataset-tools/blob/add-license-1/metadata/category_mapping.tsv, and then tried to use the updated scripts, but got the error.

```
Traceback (most recent call last):                                                                                        
  File "process_matterport.py", line 62, in <module>                                                
    label_from='raw_category', label_to='nyu40id')                                                        
  File "/home/mp3d/votenet/mp3d/scannet_utils.py", line 40, in read_label_mapping               
    mapping[row[label_from]] = int(row[label_to])                                                                                   
ValueError: invalid literal for int() with base 10: ''
```

It seems that `scannet_utils.read_label_mapping` can not well convert raw_category to nyu40id (some nyu40id is empty string). So I just add an exception line.
```
  try:
      mapping[row[label_from]] = int(row[label_to])
  except:
      mapping[row[label_from]] = -1
```

Then I got a new error.
```
Traceback (most recent call last):
  File "process_matterport.py", line 95, in <module>
    obj_pc = mesh_vertices[instance_ids==obj_id, 0:3]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 131227 but corresponding boolean dimension is 255022
```

Could you please suggest a way to fix it? Thanks!

**Comment by zaiweizhang** [comment]
I did not upload the correct data processing file. Sorry about that!
I have now updated it. Please check again.

**Comment by memoiry** [comment]
Hi, @zaiweizhang 

Thanks. I just have tried, though it works for most cases. But for some cases, it got an error (eg. y3sRwLe3Va region20).

```
Traceback (most recent call last):
  File "process.py", line 130, in <module>
    label_id = label_map[label]
KeyError: 'workbench'
```

I use the mapping from there https://github.com/matterport/3d-dataset-tools/blob/add-license-1/metadata/category_mapping.tsv.

**Comment by memoiry** [comment]
I just added one line `label_map['workbench'] = label_map['work bench']` and it works. Though i'm not sure it's a correct way.

**Comment by zaiweizhang** [comment]
Hi, I used the matterport v1[https://github.com/niessner/Matterport](url), which consists of 90 properties. I did not find y3sRwLe3Va.

**Comment by memoiry** [comment]
Hi @zaiweizhang . Sorry, that's a typo (I have checked that the version is v1). It should be 7y3sRwLe3Va. 

Now I'm getting `KeyError: 'storage'` for `8WUmhLawc2A region2`. Not sure how to fix it..

**Comment by zaiweizhang** [comment]
Sorry for taking this long to reply. I have updated the script and run it once locally.
It should not cause any problems now.

**Comment by imisra** [comment]
@memoiry - Can you confirm that it works for you now?

**Comment by imisra** [comment]
Closing because of no activity.
