### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by iswarup** [facebookresearch/DepthContrast#35]
As instructed in the README.md, I tried below steps

1. `git clone --recursive https://github.com/facebookresearch/DepthContrast.git `
2. `cd (third_party/) pointnet2`
3. `python setup.py install`

But I'm facing the below error
`Traceback (most recent call last):
  File "D:\repos\DepthContrast\third_party\pointnet2\setup.py", line 22, in <module>
    CUDAExtension(
  File "C:\Users\swarup\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1047, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "C:\Users\swarup\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1186, in library_paths
    paths.append(_join_cuda_home(lib_dir))
  File "C:\Users\swarup\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 2230, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.`

I'm using

1. Windows 11
2. pip 21.2.4 (python 3.9)
3. torch 1.13.0+cu117
4. torchvision  0.14.0+cu117

I hope this is not related to CUDA version !

**Comment by kibazhang** [comment]
I think this just means that your CUDA_HOME path is not set.
